export const defaultInputProps = {
  variant: 'outlined',
  size: 'small',
  fullWidth: true
};

export const directorates = [
  'ADG (Hort)',
  'D (Buildings)',
  'D (Electrical)',
  'D (Eng RMT)',
  'D (Engg: Roads)',
  'D (Admin)',
  'D (BCA) RMT',
  'D (Coord:) PIU BRT',
  'D (E.M)',
  'D (Finance)',
  'D (I.T)',
  'D (Machinery)',
  'D (NPV)',
  'D (Reach-II BRT)',
  'D (Vigilance)',
  'D (W&S)',
  'DG Secretariat',
  'LAC',
  'Legal Section'
];
export const userStatuses = ['active', 'block'];
export const userRole = ['operator', 'admin', 'director'];
export const districts = [
  'Abbottabad District',
  'Allai District',
  'Bajaur District',
  'Bannu District',
  'Battagram District',
  'Buner District',
  'Central Dir District',
  'Charsadda District',
  'Dera Ismail Khan District',
  'Hangu District',
  'Haripur District',
  'Karak District',
  'Khyber District',
  'Kohat District',
  'Kolai-Palas District',
  'Kurram District',
  'Lakki Marwat District',
  'Lower Chitral District',
  'Lower Dir District',
  'Lower Kohistan District',
  'Lower South Waziristan District',
  'Malakand District',
  'Mansehra District',
  'Mardan District',
  'Mohmand District',
  'North Waziristan District',
  'Nowshera District',
  'Orakzai District',
  'Peshawar District',
  'Shangla District',
  'Swabi District',
  'Swat District',
  'Tank District',
  'Torghar District',
  'Upper Chitral District',
  'Upper Dir District',
  'Upper Kohistan District',
  'Upper South Waziristan District'
];
export const Banks = [
  'AlBaraka Bank (Pakistan) Limited',
  'Allied Bank Limited',
  'Askari Bank Limited',
  'Bank AL Habib Limited',
  'Bank Alfalah Limited',
  'The Bank of Khyber',
  'The Bank of Punjab',
  'BankIslami Pakistan Limited',
  'Citibank  N.A',
  'Deutsche Bank AG',
  'Dubai Islamic Bank Pakistan Limited',
  'Faysal Bank Limited',
  'First Women Bank Limited',
  'Habib Bank Limited',
  'Habib Metropolitan Bank Limited',
  'Industrial and Commercial Bank of China Limited',
  'Industrial Development Bank of Pakistan',
  'JS Bank Limited',
  'Meezan Bank Limited',
  'MCB Bank Limited',
  'MCB Islamic Bank',
  'National Bank of Pakistan',
  'Punjab Provincial Cooperative Bank Ltd',
  'Samba Bank Limited ',
  'Sindh Bank Limited',
  'Silkbank Limited',
  'SME Bank Limited',
  'Soneri Bank Limited',
  'Standard Chartered Bank (Pakistan) Ltd',
  'Summit Bank Limited',
  'The Bank of Tokyo-Mitsubishi UFJ  Ltd',
  'United Bank Limited',
  'Zarai Taraqiati Bank Ltd'
];
